apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: l6l4cbqrz-python 
  janus-idp.io/tekton: l6l4cbqrz-python
  backstage.io/kubernetes-id: l6l4cbqrz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l6l4cbqrz-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  